### ISSUE TITLE
Installation and compilation

### ISSUE THREAD

**Issue by artemii-yanushevskyi** [ikorotkin/gromacs_fhmd#1]
Hello,

I would like to make some changes to the code. Could you refer me to the installation and compilation process of this version of gromacs? 

Thank you

Best, Artemii

**Comment by ikorotkin** [comment]
Hi Artemii,

This version of Gromacs can be compiled and installed the same way as original Gromacs without any modifications:

http://manual.gromacs.org/documentation/2016-current/install-guide/index.html

I hope this will help.

Kind regards,
Ivan
